In [3]:
import pandas as pd

In [4]:
csv_path = '../../data/clean_insurance.csv'
df = pd.read_csv(csv_path)

In [5]:
X = df.drop('charges', axis=1) #Dataframe without charges
Y = df['charges'] #Target variable Series

In [6]:
X.sample(5)

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
211,18,26.730,0,False,False,False,True,False
359,32,30.030,1,True,False,False,True,False
537,56,25.300,0,False,False,False,False,True
1132,20,33.300,0,False,False,False,False,True
403,57,30.495,0,False,False,True,False,False

In [7]:
Y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [8]:
#Creating Interaction Feature for Linear Models
X['bmi_smoker'] = X['bmi'] * X['smoker_yes']
X['age_smoker'] = X['age'] * X['smoker_yes']
X['age_bmi'] = X['age'] * X['bmi']

In [9]:
X.head()

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest,bmi_smoker,age_smoker,age_bmi
0,19,27.900,0,False,True,False,False,True,27.9,19,530.100
1,18,33.770,1,True,False,False,True,False,0.0,0,607.860
2,28,33.000,3,True,False,False,True,False,0.0,0,924.000
3,33,22.705,0,True,False,True,False,False,0.0,0,749.265
4,32,28.880,0,True,False,True,False,False,0.0,0,924.160

In [10]:
#Scaling numeric feature (Standard Scalar)
from sklearn.preprocessing import StandardScaler
num_cols = ['age', 'bmi', 'children', 'bmi_smoker', 'age_smoker', 'age_bmi']
scaleStandard = StandardScaler()
X_scaled = X.copy()
X_scaled[num_cols] = scaleStandard.fit_transform(X[num_cols])

In [11]:
X_scaled.head(5)

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest,bmi_smoker,age_smoker,age_bmi
0,-1.421407,-0.357841,-0.892872,False,True,False,False,True,2.984075,1.179609,-1.266177
1,-1.492543,0.643111,-0.070327,True,False,False,True,False,-0.358016,-0.335389,-1.114563
2,-0.781184,0.511811,1.574764,True,False,False,True,False,-0.358016,-0.335389,-0.498160
3,-0.425504,-1.243693,-0.892872,True,False,True,False,False,-0.358016,-0.335389,-0.838854
4,-0.496640,-0.190732,-0.892872,True,False,True,False,False,-0.358016,-0.335389,-0.497848

In [12]:
#Export to final csv
df_final = X_scaled.copy()
df_final['charges'] = Y
df_final.to_csv('../data/insurance_scaled_final.csv', index=False)

OSError: Cannot save file into a non-existent directory: '../data'

In [ ]:
print(df_final.columns)

Index(['age', 'bmi', 'children', 'sex_male', 'smoker_yes', 'region_northwest',
       'region_southeast', 'region_southwest', 'bmi_smoker', 'age_smoker',
       'age_bmi', 'charges'],
      dtype='object')